# Challenge 2

In this challenge we will continue working with the `Pokemon` dataset. We will attempt solving a slightly more complex problem in which we will practice the iterative data analysis process you leaned in [this video](https://www.youtube.com/watch?v=xOomNicqbkk).

The problem statement is as follows:

**You are at a Pokemon black market planning to buy a Pokemon for battle. All Pokemon are sold at the same price and you can only afford to buy one. You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either `Type 1` or `Type 2`. Which type should you choose in order to maximize your chance of receiving a good Pokemon?**

To remind you about the 3 steps of iterative data analysis, they are:

1. Setting Expectations
1. Collecting Information
1. Reacting to Data / Revising Expectations

Following the iterative process, we'll guide you in completing the challenge.


## Problem Solving Iteration 1

In this iteration we'll analyze the problem and identify the breakthrough. The original question statement is kind of vague because we don't know what a *good pokemon* really means as represented in the data. We'll start by understanding the dataset and see if we can find some insights.

In [1]:
# Import libraries
import numpy as np
import pandas as pd

In [2]:
# Importing the dataset
pokemon = pd.read_csv("Pokemon.csv")
display(pokemon.head())
pokemon.shape

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

(800, 13)

# reset Index or drop column #. i prefer to drop # rather than restting index

In [3]:
pokemon = pokemon.drop(["#"], axis=1)
pokemon

Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0                Bulbasaur    Grass  Poison    318  45      49       49   
1                  Ivysaur    Grass  Poison    405  60      62       63   
2                 Venusaur    Grass  Poison    525  80      82       83   
3    VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4               Charmander     Fire     NaN    309  39      52       43   
..                     ...      ...     ...    ...  ..     ...      ...   
795                Diancie     Rock   Fairy    600  50     100      150   
796    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

From the data it seems whether a pokemon is good depends on its abilities as represented in the fields of `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total`. We are not sure about `Generation` and `Legendary` because they are not necessarily the decisive factors of the pokemon abilities.

But `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total` are a lot of fields! If we look at them all at once it's very complicated. This isn't Mission Impossible but it's ideal that we tackle this kind of problem after we learn Machine Learning (which you will do in Module 3). For now, is there a way to consolidate the fields we need to look into?

Fortunately there seems to be a way. It appears the `Total` field is computed based on the other 6 fields. But we need to prove our theory. If we can approve there is a formula to compute `Total` based on the other 6 abilities, we only need to look into `Total`.

We have the following expectation now:

#### The `Total` field is computed based on `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, and `Speed`.

We need to collect the following information:

* **What is the formula to compute `Total`?**
* **Does the formula work for all pokemon?**

In the cell below, make a hypothesis on how `Total` is computed and test your hypothesis.

In [4]:
def totalling(x):
    sumx = x["HP"] + x["Attack"] + x["Defense"] + x["Sp. Atk"] + x["Sp. Def"] +x["Speed"] 
    return sumx

In [5]:
pokemon["Total_test"] = pokemon.apply(totalling, axis=1)
pokemon["Total_test"]

0      318
1      405
2      525
3      625
4      309
      ... 
795    600
796    700
797    600
798    680
799    600
Name: Total_test, Length: 800, dtype: int64

In [6]:
#For is null values (NaN)
pokemon.isna()

Name  Type 1  Type 2  Total     HP  Attack  Defense  Sp. Atk  Sp. Def  \
0    False   False   False  False  False   False    False    False    False   
1    False   False   False  False  False   False    False    False    False   
2    False   False   False  False  False   False    False    False    False   
3    False   False   False  False  False   False    False    False    False   
4    False   False    True  False  False   False    False    False    False   
..     ...     ...     ...    ...    ...     ...      ...      ...      ...   
795  False   False   False  False  False   False    False    False    False   
796  False   False   False  False  False   False    False    False    False   
797  False   False   False  False  False   False    False    False    False   
798  False   False   False  False  False   False    False    False    False   
799  False   False   False  False  False   False    False    False    False   

     Speed  Generation  Legendary  Total_test  
0    False       False      False       False  
1    False       False      False       False  
2    False       False      False       False  
3    False       False      False       False  
4    False       False      False       False  
..     ...         ...        ...         ...  
795  False       False      False       False  
796  False       False      False       False  
797  False       False      False       False  
798  False       False      False       False  
799  False       False      False       False  

[800 rows x 13 columns]

# Explore, Clean, and fillna (Type 2)

In [7]:
# your code here
display(pokemon["Type 2"].dtypes)
display(pokemon["Type 2"].unique())
pokemon["Type 2"].value_counts(dropna=False)

dtype('O')

array(['Poison', nan, 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
       'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
       'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'], dtype=object)

NaN         386
Flying       97
Ground       35
Poison       34
Psychic      33
Fighting     26
Grass        25
Fairy        23
Steel        22
Dark         20
Dragon       18
Ice          14
Rock         14
Water        14
Ghost        14
Fire         12
Electric      6
Normal        4
Bug           3
Name: Type 2, dtype: int64

In [8]:
#Replace NaN with the most frequent value in column vehicle class
pokemon['Type 2'] = pokemon['Type 2'].fillna("Flying")

# Explore and drop columns (Generation & Legendary)

In [9]:
#Exploring columns which looks like categorical
pokemon["Generation"].unique()
pokemon["Generation"].value_counts(dropna=False)

1    166
5    165
3    160
4    121
2    106
6     82
Name: Generation, dtype: int64

In [10]:

pokemon["Legendary"].value_counts(dropna=False)

False    735
True      65
Name: Legendary, dtype: int64

In [11]:
# just drop "Generation and Legengendary" your code here

pokemon = pokemon.drop(["Generation", "Legendary"], axis=1)
pokemon.head()

Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
0              Bulbasaur  Grass  Poison    318  45      49       49       65   
1                Ivysaur  Grass  Poison    405  60      62       63       80   
2               Venusaur  Grass  Poison    525  80      82       83      100   
3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123      122   
4             Charmander   Fire  Flying    309  39      52       43       60   

   Sp. Def  Speed  Total_test  
0       65     45         318  
1       80     60         405  
2      100     80         525  
3      120     80         625  
4       50     65         309

# Get independent (X) and dependent (y) values

In [12]:
y = pokemon["Total"]
X = pokemon.drop(["Total"], axis=1)
# Drop "Name" column from X-cat since it does not have multiple categories
#X_cat= X_cat.drop(["Name"], axis=1)
#X_cat.head(4)

In [13]:
display(y.head())
X

0    318
1    405
2    525
3    625
4    309
Name: Total, dtype: int64

Name   Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0                Bulbasaur    Grass  Poison  45      49       49       65   
1                  Ivysaur    Grass  Poison  60      62       63       80   
2                 Venusaur    Grass  Poison  80      82       83      100   
3    VenusaurMega Venusaur    Grass  Poison  80     100      123      122   
4               Charmander     Fire  Flying  39      52       43       60   
..                     ...      ...     ...  ..     ...      ...      ...   
795                Diancie     Rock   Fairy  50     100      150      100   
796    DiancieMega Diancie     Rock   Fairy  50     160      110      160   
797    HoopaHoopa Confined  Psychic   Ghost  80     110       60      150   
798     HoopaHoopa Unbound  Psychic    Dark  80     160       60      170   
799              Volcanion     Fire   Water  80     110      120      130   

     Sp. Def  Speed  Total_test  
0         65     45         318  
1         80     60         405  
2        100     80         525  
3        120     80         625  
4         50     65         309  
..       ...    ...         ...  
795      150     50         600  
796      110    110         700  
797      130     70         600  
798      130     80         680  
799       90     70         600  

[800 rows x 10 columns]

# Seperating data file into numerical and categorical

In [14]:
# For numerical independent
X_num = pokemon._get_numeric_data()
X_num.head()

Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Total_test
0    318  45      49       49       65       65     45         318
1    405  60      62       63       80       80     60         405
2    525  80      82       83      100      100     80         525
3    625  80     100      123      122      120     80         625
4    309  39      52       43       60       50     65         309

In [15]:
# Getting categorical and numerical
X_cat = pokemon.select_dtypes('object')
X_cat.head()

Name Type 1  Type 2
0              Bulbasaur  Grass  Poison
1                Ivysaur  Grass  Poison
2               Venusaur  Grass  Poison
3  VenusaurMega Venusaur  Grass  Poison
4             Charmander   Fire  Flying

In [16]:
# Drop "Name" column from X-cat since it does not have multiple categories
X_cat= X_cat.drop(["Name"], axis=1)
X_cat.head(4)

Type 1  Type 2
0  Grass  Poison
1  Grass  Poison
2  Grass  Poison
3  Grass  Poison

## Problem Solving Iteration 2

Now that we have consolidated the abilities fields, we can update the problem statement. The new problem statement is:

### Which pokemon type is most likely to have the highest `Total` value?

In the updated problem statement, we assume there is a certain relationship between the `Total` and the pokemon type. But we have two *type* fields (`Type 1` and `Type 2`) that have string values. In data analysis, string fields have to be transformed to numerical format in order to be analyzed. 

In addition, keep in mind that `Type 1` always has a value but `Type 2` is sometimes empty (having the `NaN` value). Also, the pokemon type we choose may be either in `Type 1` or `Type 2`.

Now our expectation is:

#### `Type 1` and `Type 2` string variables need to be converted to numerical variables in order to identify the relationship between `Total` and the pokemon type.

The information we need to collect is:

#### How to convert two string variables to numerical?

Let's address the first question first. You can use a method called **One Hot Encoding** which is frequently used in machine learning to encode categorical string variables to numerical. The idea is to gather all the possible string values in a categorical field and create a numerical field for each unique string value. Each of those numerical fields uses `1` and `0` to indicate whether the data record has the corresponding categorical value. A detailed explanation of One Hot Encoding can be found in [this article](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f). You will formally learn it in Module 3.

For instance, if a pokemon has `Type 1` as `Poison` and `Type 2` as `Fire`, then its `Poison` and `Fire` fields are `1` whereas all other fields are `0`. If a pokemon has `Type 1` as `Water` and `Type 2` as `NaN`, then its `Water` field is `1` whereas all other fields are `0`.

#### In the next cell, use One Hot Encoding to encode `Type 1` and `Type 2`. Use the pokemon type values as the names of the numerical fields you create.

The new numerical variables you create should look like below:

![One Hot Encoding](../images/one-hot-encoding.png)

In [17]:
pokemon_types = X_cat
pokemon_types

Type 1  Type 2
0      Grass  Poison
1      Grass  Poison
2      Grass  Poison
3      Grass  Poison
4       Fire  Flying
..       ...     ...
795     Rock   Fairy
796     Rock   Fairy
797  Psychic   Ghost
798  Psychic    Dark
799     Fire   Water

[800 rows x 2 columns]

# using pd.get_dummies

In [29]:
pokemon_types
dummycoded_pokemon_types =  pd.get_dummies(pokemon_types, 
                             columns=["Type 1", "Type 2"],
                             drop_first=True)

display(list(zip(list(pokemon_types.columns),list(dummycoded_pokemon_types.columns))))

dummycoded_pokemon_types.head()


[('Type 1', 'Type 1_Dark'), ('Type 2', 'Type 1_Dragon')]

Type 1_Dark  Type 1_Dragon  Type 1_Electric  Type 1_Fairy  Type 1_Fighting  \
0            0              0                0             0                0   
1            0              0                0             0                0   
2            0              0                0             0                0   
3            0              0                0             0                0   
4            0              0                0             0                0   

   Type 1_Fire  Type 1_Flying  Type 1_Ghost  Type 1_Grass  Type 1_Ground  ...  \
0            0              0             0             1              0  ...   
1            0              0             0             1              0  ...   
2            0              0             0             1              0  ...   
3            0              0             0             1              0  ...   
4            1              0             0             0              0  ...   

   Type 2_Ghost  Type 2_Grass  Type 2_Ground  Type 2_Ice  Type 2_Normal  \
0             0             0              0           0              0   
1             0             0              0           0              0   
2             0             0              0           0              0   
3             0             0              0           0              0   
4             0             0              0           0              0   

   Type 2_Poison  Type 2_Psychic  Type 2_Rock  Type 2_Steel  Type 2_Water  
0              1               0            0             0             0  
1              1               0            0             0             0  
2              1               0            0             0             0  
3              1               0            0             0             0  
4              0               0            0             0             0  

[5 rows x 34 columns]

### Arrangement of columns not the same after using get-dummies. I'ld rather go for Onehot-encoding

# Using Onehot endcoding

In [19]:
import math
from sklearn import linear_model

In [20]:
# One Hot encoding used to turn categorical variables to numerical columns
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first').fit(X_cat)
print(encoder.categories_)
encoded = encoder.transform(X_cat).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded)
onehot_encoded.head()

[array(['Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting', 'Fire',
       'Flying', 'Ghost', 'Grass', 'Ground', 'Ice', 'Normal', 'Poison',
       'Psychic', 'Rock', 'Steel', 'Water'], dtype=object), array(['Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting', 'Fire',
       'Flying', 'Ghost', 'Grass', 'Ground', 'Ice', 'Normal', 'Poison',
       'Psychic', 'Rock', 'Steel', 'Water'], dtype=object)]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


0    1    2    3    4    5    6    7    8    9   ...   24   25   26   27  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    28   29   30   31   32   33  
0  0.0  1.0  0.0  0.0  0.0  0.0  
1  0.0  1.0  0.0  0.0  0.0  0.0  
2  0.0  1.0  0.0  0.0  0.0  0.0  
3  0.0  1.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 34 columns]

## Problem Solving Iteration 3

Now we have encoded the pokemon types, we will identify the relationship between `Total` and the encoded fields. Our expectation is:

#### There are relationships between `Total` and the encoded pokemon type variables and we need to identify the correlations.

The information we need to collect is:

#### How to identify the relationship between `Total` and the encoded pokemon type fields?

There are multiple ways to answer this question. The easiest way is to use correlation. In the cell below, calculate the correlation of `Total` to each of the encoded fields. Rank the correlations and identify the #1 pokemon type that is most likely to have the highest `Total`.

In [21]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

# For correlation Concatenate "Total and encoded"

In [35]:

concat_onehot_enncoded = pd.concat([y, onehot_encoded], axis=1)  
concat_onehot_enncoded.head()

Total    0    1    2    3    4    5    6    7    8  ...   24   25   26  \
0    318  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
1    405  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
2    525  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
3    625  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
4    309  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    27   28   29   30   31   32   33  
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 35 columns]

In [36]:
types_correlations_matrix = concat_onehot_enncoded.corr()
types_correlations_matrix 

Total         0         1         2         3         4         5  \
Total  1.000000  0.017818  0.196532  0.016715 -0.026948 -0.029086  0.050527   
0      0.017818  1.000000 -0.040984 -0.048438 -0.029584 -0.037524 -0.052938   
1      0.196532 -0.040984  1.000000 -0.049245 -0.030077 -0.038149 -0.053820   
2      0.016715 -0.048438 -0.049245  1.000000 -0.035547 -0.045088 -0.063609   
3     -0.026948 -0.029584 -0.030077 -0.035547  1.000000 -0.027538 -0.038850   
4     -0.029086 -0.037524 -0.038149 -0.045088 -0.027538  1.000000 -0.049277   
5      0.050527 -0.052938 -0.053820 -0.063609 -0.038850 -0.049277  1.000000   
6      0.029504 -0.014233 -0.014470 -0.017102 -0.010445 -0.013248 -0.018691   
7      0.007594 -0.040984 -0.041667 -0.049245 -0.030077 -0.038149 -0.053820   
8     -0.036057 -0.062173 -0.063209 -0.074706 -0.045628 -0.057873 -0.081647   
9      0.004082 -0.040984 -0.041667 -0.049245 -0.030077 -0.038149 -0.053820   
10    -0.002412 -0.035310 -0.035898 -0.042427 -0.025913 -0.032868 -0.046369   
11    -0.104150 -0.075017 -0.076267 -0.090138 -0.055054 -0.069829 -0.098513   
12    -0.057123 -0.038237 -0.038874 -0.045945 -0.028062 -0.035593 -0.050214   
13     0.094364 -0.055611 -0.056538 -0.066820 -0.040812 -0.051765 -0.073029   
14     0.037524 -0.048438 -0.049245 -0.058201 -0.035547 -0.045088 -0.063609   
15     0.082000 -0.037524 -0.038149 -0.045088 -0.027538 -0.034929 -0.049277   
16    -0.015640 -0.081009 -0.082359 -0.097338 -0.059451 -0.075406 -0.106381   
17     0.065844 -0.032150 -0.032686 -0.038631 -0.023595  0.014409 -0.042220   
18     0.115240  0.100556 -0.030969  0.000370 -0.022355 -0.028355 -0.005812   
19     0.014669 -0.017454  0.056190 -0.020972 -0.012809 -0.016246 -0.022920   
20    -0.024606 -0.034544  0.003054 -0.008695 -0.025351 -0.032155 -0.045363   
21     0.138726  0.036251 -0.037412 -0.044216 -0.027006 -0.034254  0.151836   
22     0.073234  0.135074  0.027289  0.015337 -0.018183 -0.023063 -0.032537   
23    -0.153896 -0.049209 -0.030257  0.060926  0.119371  0.066496  0.027005   
24    -0.004885  0.071991 -0.027243  0.009617 -0.019665 -0.024943 -0.035189   
25    -0.039224 -0.036061 -0.036662 -0.011817 -0.026464 -0.033567 -0.047355   
26     0.016486 -0.042946  0.112272 -0.051602 -0.031517 -0.039976  0.017973   
27     0.100870  0.071991  0.118700  0.009617 -0.019665 -0.024943 -0.035189   
28    -0.013956 -0.014233 -0.014470  0.138368 -0.010445 -0.013248  0.125084   
29    -0.067837 -0.042300 -0.043005 -0.050827 -0.031043 -0.039375 -0.055549   
30     0.076054  0.023490  0.085964 -0.050041 -0.030563  0.065654 -0.003697   
31    -0.000512 -0.026796 -0.027243 -0.032197 -0.019665 -0.024943  0.003480   
32     0.070307  0.045446 -0.034325  0.060014 -0.024778  0.053226 -0.013332   
33    -0.018800 -0.026796 -0.027243  0.009617 -0.019665 -0.024943  0.003480   

              6         7         8  ...        24        25        26  \
Total  0.029504  0.007594 -0.036057  ... -0.004885 -0.039224  0.016486   
0     -0.014233 -0.040984 -0.062173  ...  0.071991 -0.036061 -0.042946   
1     -0.014470 -0.041667 -0.063209  ... -0.027243 -0.036662  0.112272   
2     -0.017102 -0.049245 -0.074706  ...  0.009617 -0.011817 -0.051602   
3     -0.010445 -0.030077 -0.045628  ... -0.019665 -0.026464 -0.031517   
4     -0.013248 -0.038149 -0.057873  ... -0.024943 -0.033567 -0.039976   
5     -0.018691 -0.053820 -0.081647  ... -0.035189 -0.047355  0.017973   
6      1.000000 -0.014470 -0.021951  ... -0.009461 -0.012732 -0.015163   
7     -0.014470  1.000000 -0.063209  ... -0.027243  0.329956 -0.043661   
8     -0.021951 -0.063209  1.000000  ... -0.041328 -0.055617 -0.044608   
9     -0.014470 -0.041667 -0.063209  ...  0.070052 -0.036662 -0.043661   
10    -0.012467 -0.035898 -0.054458  ...  0.032412 -0.031586  0.069859   
11    -0.026486 -0.076267 -0.115700  ... -0.049865 -0.023282 -0.061279   
12    -0.013500 -0.038874 -0.058974  ... -0.025417 -0.034205  0.025771   
13    -0.019634 -0.056538 -0.085769  ...  0.000093 -0.0

In [40]:
# your code here
print(types_correlations_matrix ["Total"].sort_values(ascending=False))

Total    1.000000
1        0.196532
21       0.138726
18       0.115240
27       0.100870
13       0.094364
15       0.082000
30       0.076054
22       0.073234
32       0.070307
17       0.065844
5        0.050527
14       0.037524
6        0.029504
0        0.017818
2        0.016715
26       0.016486
19       0.014669
7        0.007594
9        0.004082
31      -0.000512
10      -0.002412
24      -0.004885
28      -0.013956
16      -0.015640
33      -0.018800
20      -0.024606
3       -0.026948
4       -0.029086
8       -0.036057
25      -0.039224
12      -0.057123
29      -0.067837
11      -0.104150
23      -0.153896
Name: Total, dtype: float64


# Bonus Question

Say now you can choose both `Type 1` and `Type 2` of the pokemon. In order to receive the best pokemon, which types will you choose?

In [39]:
# your code here